### PR TITLE
greengage api documentation

### PR DESCRIPTION
**Pull request by leganz**
### Added
- Basic documentation of the core principles of the graphql endpoints and the location
- Demo Code for Graphql client code
- Demo Code for RESTful to GraphQL (complete demo project included)

### CODE REVIEW

**Comment by leganz** [comment]
Don't know why this security check fails - i do not have added docs/tools/wordpress ...

**Comment by fvergaracl** [comment]
> Don't know why this security check fails - i do not have added docs/tools/wordpress ...

Don't worry about this, I have reviewed the commit and there is no sensitive information exposed.

I have given you the permissions over it repo, so you can merge inside the main branch when you consider everything is ready to merge

**Comment by leganz** [comment]
@fvergaracl it seems I do not have the permission to merge :/

**Comment by fvergaracl** [comment]
> @fvergaracl it seems I do not have the permission to merge :/

You're right . I sent you an invitation a few minutes ago . After your accept this invitation, you could do the merge

**Pull request merged**
